# SITE CONFIGURATION
title: >
author: Sylvain White
description: > # Meta description of Homepage
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://francinehemmings.com/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Francine Hemmimgs
  links:
    - https://www.linkedin.com/in/francine-hemmmings-d-o-06a868161

# THEME SETTINGS
home_links: # Navigation links for languages
  fr-CA:
    {name: "Français", link: "fr-CA/index"} 
  en-US:
    {name: "English", link: "en-US/index"} 

navigation_links: # Navigation links
  fr-CA:
    - {name: "Accueil", link: "fr-CA/index"}
    - {name: "Qui est Francine?", link: "fr-CA/whoIsFrancine"}
    - {name: "Tarifs", link: "fr-CA/rates"}
    - {name: "Contact", link: "fr-CA/contact"}   
  en-US:
    - {name: "Home", link: "en-US/index"}
    - {name: "Who is Francine?", link: "en-US/whoIsFrancine"}
    - {name: "Rates", link: "en-US/rates"}
    - {name: "Contact", link: "en-US/contact"}

translation:
  fr-CA:
    copyright: "Tous droits réservés."
    form_name_text: "Nom"
    form_email_text: "Courriel"
    form_message_text: "Message"
    form_send_text: "Envoyer"
    message_404: "Oups... Désolé. Veuillez aller à la page d'accueil et recommencer!"
  en-US:
    copyright: "All rights rserved."   
    form_name_text: "Name"
    form_email_text: "Email"
    form_message_text: "Message"
    form_send_text: "Send"
    message_404: "Ups... Sorry. Please go back to the Home page and start over!"    

hero_img: # Main background image: use the path from /assets/img/
  fr-CA: posts/francineHemmings_homepage_fr.jpg 
  en-US: posts/francineHemmings_homepage_en.jpg 

# Jekyll is a great tool to create static sites, but there’s no backend to send your
# data to. However, you can use free SaaS as a backend for forms, such as Formspree 
# to handle form submissions. Sleek has a configured form using formspree ready for you.
# All you have to do is change the email in .config.yml.
email: osteopathie@francinehemmings.com # email for form submission

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem

exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
